Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine319"
  config.vm.synced_folder ".", "/vagrant"
  config.vbguest.auto_update = false
  config.vm.define "jbuanS" do |control|
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
      v.name = "jbuanS"
      v.memory = "1024"
      v.cpus = "1"
      v.customize ["modifyvm", :id, "--cableconnected1", "on"]
    end
    control.vm.provision "shell", inline: <<-SHELL
      apk update
      apk upgrade
      apk add iptables
      #je crois que cette ligne fait tout serrer alors je l'ai enlevé ->  --r le chemin du fichier à modifier
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode=644 --node-name=jbuanS --tls-san=192.168.56.110 -i=192.168.56.110 --cluster-cidr=192.168.56.0/30 " sh -s - server 
      NODE_TOKEN="/var/lib/rancher/k3s/server/token"
      while [ ! -e ${NODE_TOKEN} ]
        do
          sleep 2
        done
      cp ${NODE_TOKEN} /vagrant/.
      chmod 644 /etc/rancher/k3s/k3s.yaml
      # Effectuer le remplacement de texte en utilisant sed
      cp /etc/rancher/k3s/k3s.yaml /vagrant/.
      mkdir /home/vagrant/.kube
      cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
      chown vagrant /home/vagrant/.kube/config
      chmod 600 /home/vagrant/.kube/config
      export KUBECONFIG=/home/vagrant/.kube/config
    SHELL
  end
  config.vm.define "jbuanSW" do |control|
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |v|
      v.name = "jbuanSW"
      v.memory = "1024"
      v.cpus = "1"
      v.customize ["modifyvm", :id, "--cableconnected1", "on"]
    end
    control.vm.provision "file", source:"token", destination:"/home/vagrant/.kube/token"
    control.vm.provision "file", source: "k3s.yaml", destination: "/home/vagrant/.kube/config"
    control.vm.provision "shell", inline: <<-SHELL
      apk update
      apk upgrade
      apk add iptables
      #export NODE_TOKEN="/home/vagrant/.kube/token"
      sudo sed -i 's#server: https://127\.0\.0\.1:6443#server: https://192\.168\.56\.110:6443#g' /home/vagrant/.kube/config
      export KUBECONFIG="/home/vagrant/.kube/config"
      export K3S_CONFIG_FILE="/home/vagrant/.kube/config"
#     curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent -i=192.158.56.111" K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=${NODE_TOKEN} K3S_NODE_NAME=jbuanSW sh -
      sudo curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent -i=192.158.56.111 --node-name=jbuanSW --token-file=/home/vagrant/.kube/token -s=https://192.168.56.110:6443" sh -
      sudo k3s agent -i=192.168.56.111 --node-name=jbuanSW --token-file=/home/vagrant/.kube/token -s=https://192.168.56.110:6443
    # En procédant ainsi, on n'a plus qu'a ce connecte en vagrant ssh au server et sudo kubectl get node. Le worker sera blinde de rouge though
    SHELL
  end
end  
