apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap2
data:
  index.html: |
    <html>
    <h1>Welcome! This is Deployment Two, acting as the home decor website. </h1>
    </html>
  default.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  192.168.56.110;

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }
